Repository icesat2py/icepyx, pull requests merged in 2024-09, with the labels that each got.

#581 Reinstate test_download_granules_without_subsetting
  icepyx/core/granules.py
  icepyx/tests/test_behind_NSIDC_API_login.py
Labels: afternoon_contribution

#606 [docs] traffic updates May-Aug 2024
  doc/source/tracking/pypistats/downloads.svg
  doc/source/tracking/pypistats/downloads_data.csv
  doc/source/tracking/pypistats/sys_downloads_data.csv
  doc/source/tracking/traffic/clones.csv
  doc/source/tracking/traffic/plots.svg
  doc/source/tracking/traffic/views.csv
Labels: review::quick, review::priority

#603 Add v1.x deprecation warning
  icepyx/__init__.py
Labels: review::quick, review::priority

#593 Typecheck some API interfaces
  .github/workflows/typecheck.yml
  doc/source/conf.py
  doc/source/index.rst
  doc/source/user_guide/documentation/icepyx.rst
  doc/source/user_guide/documentation/types.rst
  icepyx/core/APIformatting.py
  icepyx/core/auth.py
  icepyx/core/granules.py
  icepyx/core/query.py
  icepyx/core/types.py
  icepyx/core/visualization.py
  pyproject.toml
  requirements-dev.txt
  requirements-docs.txt
Labels: review::priority

#609 Mark tests which depend on ECS as expected fail; separate integration and unit tests
  .github/workflows/integration_test.yml
  .github/workflows/unit_test.yml
  doc/source/user_guide/documentation/classes_dev_uml.svg
  doc/source/user_guide/documentation/classes_user_uml.svg
  doc/source/user_guide/documentation/packages_user_uml.svg
  icepyx/tests/__init__.py
  icepyx/tests/integration/ATL06v06_options.json
  icepyx/tests/integration/test_auth.py
  icepyx/tests/integration/test_behind_NSIDC_API_login.py
  icepyx/tests/unit/test_APIformatting.py
  icepyx/tests/unit/test_Earthdata.py
  icepyx/tests/unit/test_granules.py
  icepyx/tests/unit/test_is2class_query.py
  icepyx/tests/unit/test_is2ref.py
  icepyx/tests/unit/test_query.py
  icepyx/tests/unit/test_quest.py
  icepyx/tests/unit/test_quest_argo.py
  icepyx/tests/unit/test_read.py
  icepyx/tests/unit/test_spatial.py
  icepyx/tests/unit/test_temporal.py
  icepyx/tests/unit/test_validate_inputs.py
  icepyx/tests/unit/test_variables.py
  icepyx/tests/unit/test_visualization.py
Labels: review::quick

#616 Bugfix: Move `loop_root` sentinel value above exhaustive conditionals
  icepyx/core/granules.py
Labels: review::quick, review::priority

#590 Remove redundant conditional
  icepyx/core/APIformatting.py
Labels: review::quick

#604 Type annotate the temporal module
  doc/source/user_guide/documentation/classes_dev_uml.svg
  icepyx/core/query.py
  icepyx/core/temporal.py
Labels: review::quick
